import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../styles/theme";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Box } from "@mui/material";
import { NavLink } from "@/types/navigation";
import HomeIcon from "@mui/icons-material/Home";
import KitchenIcon from "@mui/icons-material/Kitchen";
import RestaurantMenuIcon from "@mui/icons-material/RestaurantMenu";
import MenuBookIcon from "@mui/icons-material/MenuBook";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const drawerWidth = 240;
const navlinks: NavLink[] = [
  { name: "Home", link: "/", Icon: HomeIcon },
  { name: "Storage", link: "/storage", Icon: KitchenIcon },
  { name: "Recipes", link: "/recipes", Icon: RestaurantMenuIcon },
  { name: "Meal Planner", link: "/mealplanner", Icon: MenuBookIcon },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Navbar navlinks={navlinks} drawerWidth={drawerWidth} />
            <Box
              component="main"
              sx={{
                flexGrow: 1,
                p: 1,
                width: { sm: `calc(100% - ${drawerWidth}px)` },
                mt: { xs: 8, sm: 0 },
                ml: { sm: `${drawerWidth}px` },
              }}
            >
              {children}
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
